---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nifi
  namespace: ${releaseNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  interval: 5m
  url: "${helmMirrorURL:=https://github.com/konpyutaika/nifikop}"
  ref:
    branch: master