---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nifi
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ./helm/nifikop/
      version: 0.14.1
      sourceRef:
        kind: GitRepository
        name: nifi
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
  valuesFrom:
  - kind: ConfigMap
    name: nifi-defaults